### ISSUE TITLE
Uso SolrCloud

### ISSUE THREAD

**Issue by dhiego28** [supergovbr/super-docker#39]
Sugiro o uso do SolrCloud. Um exemplo: https://github.com/aws-samples/amazon-eks-arch-apache-solr

**Comment by caduvieira** [comment]
Pelo que entendi é necessário ter acesso ao AWS e EKS. Seria possível sem ter conta lá?

**Comment by caduvieira** [comment]
Pelo que entendi no repositório é necessário ter acesso ao AWS e ao EKS. Seria possível usar sem ter acesso a uma conta da AWS?

**Comment by dhiegorocha** [comment]
Não é necessário. Apenas deve ser feita a configuração dos cores para funcionar no SolrCloud + Zookeeper. 
Hoje não está sendo possível criar uma mais uma instancia do solr porque ele não tem um core compartilhado.

**Comment by marlinhares** [comment]
Prezados vamos acompanhar na issue #43
