### ISSUE TITLE
Disponilização do módulo de loginúnico

### ISSUE THREAD

**Issue by dhiego28** [supergovbr/super-docker#40]
Solicito a disponibilização do módulo de login único para testes.

**Comment by caduvieira** [comment]
Aqui não é o repositório para solicitar esse acesso. Por favor seguir os passos para acesso ao super e, eventualmente, ao módulo do login único ou assinatura avançada. https://www.gov.br/economia/pt-br/assuntos/processo-eletronico-nacional/conteudo/super.br
