### ISSUE TITLE
Adicionar controle de cache e de compressão no apache

### ISSUE THREAD

**Issue by caduvieira** [supergovbr/super-docker#5]
Atualmente o container de apache tem os módulos de expires e deflate habilitados mas não são usados.

A sugestão de melhoria é configurar o uso dos mesmos.

**Comment by marlinhares** [comment]
Sim. Precisamos medir qual a melhor performance.
Vou subir nos proxs dias uma solução que adotamos no ME que existe um Pod apenas para cache. So que o cache q ele usa é via disco, já é um ganho mas pode ser melhor.

**Comment by caduvieira** [comment]
Ok. Caso auxilie na performance por favor aceitar o PR
