### ISSUE TITLE
Problemas na execução SEI DEV

### ISSUE THREAD

**Issue by sh4rkzy** [supergovbr/super-docker#58]
Estou com o problema quando executo o make up no qual o mesmo fica com o seguintes logs após a criação do PATH no env.env ou export SUPER_PATH, assim não tendo sucesso na execução.

Segue Logs:
`
 make up
docker-compose --env-file env.env up -d
WARN[0000] The "HOST_IP" variable is not set. Defaulting to a blank string.
[+] Running 7/7
 ✔ Network dev_default  Created                                                                    0.0s
 ✔ Container solr       Started                                                                    0.1s
 ✔ Container memcached  Started                                                                    0.1s
 ✔ Container smtp       Started                                                                    0.1s
 ✔ Container jod        Started                                                                    0.2s
 ✔ Container mysql      Started                                                                    0.2s
 ✔ Container httpd      Started                                                                    0.1s
make check-super-isalive
make[1]: Entering directory 'meu diretorio'

Vamos tentar acessar a pagina de login do SUPER, vamos aguardar por 45 segs.
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Aguardando resposta ...
make[1]: Leaving directory 'meu diretorio'`

Lembrando que meu codigo fonte do sei está a uma pasta atrás da raiz do super-docker

**Comment by caduvieira** [comment]
Dentro do env há uma variável para o diretório do SEI. O container desse repositório "super-docker" é utilizado pelo Makefile do SEI. 

Na pasta do SEI execute make up; make update. 
Após clone do repositório:

```
cd sei
make up; make update
```

Caso continue com problemas abra issue no repositório do SEI
