### ISSUE TITLE
Ajuste do Ingress para K8s

### ISSUE THREAD

**Issue by caduvieira** [supergovbr/super-docker#7]
Há alterações na API do Ingress para kubernetes 1.22+ . É necessário deixar de usar API que está deprecated.

**Comment by marlinhares** [comment]
Perfeito mestre. So q demoramos tanto pra ver o PR q ele deprecou. Acredito q as alteraces ja estejam la. Verifique se falta mais alguma coisa e resolvendo os conflitos por mim pode mergear.
